language: php

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email:
    recipients:
      - vl.schepotin@gmail.com
    on_success: always
    on_failure: always

addons:
  apt:
    packages:
    - node
    - npm
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer install
  - cp .env.example .env
  - sed -i -- "s/DB_DATABASE=homestead/DB_DATABASE=testing/g" .env
  - sed -i -- "s/DB_USERNAME=homestead/DB_USERNAME=travis/g" .env
  - sed -i -- "s/DB_PASSWORD=secret/DB_PASSWORD=/g" .env
  - sed -i -- "s/table->string('email')/table->string('email', 40)/g" database/migrations/2014_10_12_000000_create_users_table.php
  - sed -i -- "s/table->string('email')/table->string('email', 40)/g" database/migrations/2014_10_12_100000_create_password_resets_table.php
  - php artisan key:generate

script:
  - if [ -n "$TRAVIS_TAG" ]; then composer require schepotin/laravel-api; fi
  - if [ -n "$TRAVIS_BRANCH" ]; then composer require schepotin/laravel-api:dev-$TRAVIS_BRANCH; fi
  - php artisan laravel-api:publish --api --vue --no-interaction
  - php artisan migrate
  - npm install
  - npm run prod